### ISSUE TITLE
Security: Plugin opens arbitrary files outside the images path

### ISSUE THREAD

**Issue by PhrozenByte** [nliautaud/pico-pages-images#1]
https://github.com/nliautaud/pico-pages-images/blob/fa486f91785fe8e048a63c8ce9cdc7b63081c89c/PicoPagesImages.php#L34

Please keep in mind that `$url` is the raw user input and not validated in any way. Users might do requests like `http://example.com/pico/../../../../../../../../some/sensitive/file/on/your/server` ("base dir breakouts"), resulting in accessing files you don't want to be accessed. You should rather rely on the `$requestFile` variable of the `onRequestFile` event.

**Comment by PhrozenByte** [comment]
https://github.com/nliautaud/pico-pages-images/blob/fa02e59433d91671e6c6ee3f8c5bfca1253b8c8b/PicoPagesImages.php#L35-L42

Both Pico's content dir and content ext are configurable. How about something like this:

```php
     public function onRequestFile(&$requestFile) 
    {
        $contentDir = $this->getConfig('content_dir');
        $contentDirLength = strlen($contentDir);
        if (substr($requestFile, 0, $contentDirLength) === $contentDir) {
            $contentExt = $this->getConfig('content_ext');
            $this->path = substr($requestFile, $contentDirLength, -strlen($contentExt));
            $this->path = ((substr($this->path, -6) === '/index') || ($this->path === 'index')) ? (string) substr($this->path, 5) : $this->path . '/';
        }
    }
```

You should furthermore add a preliminary check in `PicoPagesImages::images_list()` whether `PicoPagesImages::$path` is empty or not:

```php
    private function images_list()
    {
        if (!$this->path) return array();
        // ...
    }
```

**#edit:** Yet another alternative: Use the `$currentPage` parameter (`$currentPage['id']`) of the `onPagesLoaded` event. However, this is probably not the best solution since many plugins modify the `$pages` array, but don't update `$currentPage`, `$nextPage` and `$previousPage`... That's the reason why there's a separate event for this in Pico 2.0.

---

And here are some "by the way" recommendations (not strictly necessary, I just want to let you know):

https://github.com/nliautaud/pico-pages-images/blob/fa02e59433d91671e6c6ee3f8c5bfca1253b8c8b/PicoPagesImages.php#L52

This isn't necessary. Pico already ensures that there is a trailing slash. You even don't need `PicoPagesImages::$base` at all - simply use `$this->getBaseUrl()`.

https://github.com/nliautaud/pico-pages-images/blob/fa02e59433d91671e6c6ee3f8c5bfca1253b8c8b/PicoPagesImages.php#L11

Plugin classes shouldn't be `final` (yes, I know, `DummyPlugin` is final - that's because I didn't want people to do `extends DummyPlugin`, however, this had the unwanted effect that people use `final` for their plugins).

https://github.com/nliautaud/pico-pages-images/blob/fa02e59433d91671e6c6ee3f8c5bfca1253b8c8b/PicoPagesImages.php#L17-L23

Plugins are enabled by default anyway, so you can remove this property :smiley:

**Comment by nliautaud** [comment]
Oh, thanks :) Totally missed those `content_dir`/ `content_ext`, I was looking for a `getContentDir()`, and didn't know that `getConfig` would return processed values. I should have been a bit less lazy on the docs. I'll clean when possible.
