### ISSUE TITLE
Various possible PHP errors/warnings

### ISSUE THREAD

**Issue by PhrozenByte** [nliautaud/pico-pages-images#2]
https://github.com/nliautaud/pico-pages-images/blob/fa486f91785fe8e048a63c8ce9cdc7b63081c89c/PicoPagesImages.php#L92-L97

* `glob()` (line 92) might return `FALSE`, resulting in a `PHP Warning:  Invalid argument supplied for foreach()` on line 94.
* `pathinfo()` (line 96) doesn't guarantee to return the array in the order and form you expect it; the code might result in a `PHP Notice:  Undefined offset` or might assign unexpected values to your variables.
* `getimagesize()` (line 97) doesn't guarantee to return a array with >= 5 items. Just two items are actually guaranteed (resulting in multiple `PHP Notice:  Undefined offset`). The function might even return `FALSE`.

**Comment by nliautaud** [comment]
Thanks !
For my information, do you have a source for `getimagesize` returning less that five items ? The doc indicates only that the sixth an seven may be missing, and uses `list()` with five items.  
https://secure.php.net/manual/en/function.getimagesize.php  
I added an `array_pad` anyway.

**Comment by PhrozenByte** [comment]
The return value of `getimagesize()` behaves pretty strange for invalid/corrupt images... Please note that `getimagesize()` might return `FALSE`, leading to a `PHP Warning:  array_pad() expects parameter 1 to be array, boolean given` with `array_pad()`. Yes, PHP can really be a pain in the ass 😒

**Comment by nliautaud** [comment]
Don't blame it form my lazyness :)
Added a check 1d53a553dc11ab8a9f89effd6b6533ca897447a1

**Comment by PhrozenByte** [comment]
Why "laziness", it's completely fine this way 😉 👍
